
/* This is the LAMBDAC Javascript runtime. It implements various
   things that the code generated by the compiler needs. */

/* XXX need an actual representation for exceptions. */
var Match = 0;

var Test0 = { x : 1 };

var Test = { x : 1 + 1 };

