
default : jumptest.exe


sdlml.o : sdlml.c
	gcc -O `sdl-config --cflags` -c sdlml.c -o sdlml.o

jumptest.exe : sdlml.o *.sml
	mlton -link-opt "-lSDL_image -ltiff -lpng -ljpeg -lz `sdl-config --libs`" -default-ann 'allowImport true' -output jumptest.exe jumptest.cm sdlml.o 
