
default : jumptest


linux.o : linux.c
	gcc -O `sdl-config --cflags` -c linux.c -o linux.o

jumptest : linux.o *.sml
	mlton -link-opt "-lSDL_image -ltiff -lpng -ljpeg -lz `sdl-config --libs`" -default-ann 'allowImport true' -output jumptest.exe jumptest.cm linux.o 
