<tr><td><a href="index.shtml"><img src="images/button-home.png" alt="home" border="0" width="88" height="17" /></a></td></tr>
<tr><td><a href="screenshots.shtml"><img src="images/button-screenshots.png" alt="screenshots" border="0" width="88" height="17" /></a></td></tr>
<tr><td><a href="download.shtml"><img src="images/button-download.png" alt="download" border="0" width="88" height="17" /></a></td></tr>
<tr><td><a href="levels.shtml"><img src="images/button-level-browser.png" alt="levels" border="0" width="88" height="17" /></a></td></tr>
<tr><td><a href="http://radar.spacebar.org/f/a/weblog/comment/1/898"><img src="images/button-feedback.png" alt="feedback" border="0" width="88" height="17" /></a></td></tr>
