<table>
<tr>
<td valign="top"><a href="/f/a/escape/level/2402"><img src="/png/24720f3db228fde29fb486d522042347.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/2402">block cipher</a>
<br />by pieguy
<br /><b>difficulty</b>: 10.00
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/670"><img src="/png/8fa772b4baa7f23f54c7efd122578a0c.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/670">Too Many Lasers</a>
<br />by Henri Kareinen
<br /><b>difficulty</b>: 9.50
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/885"><img src="/png/49f038ef5f59dbab64f8d88ca155b028.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/885"><font color="#FF756A">Rouge<font color="#000000">-Like-Like</font></font></a>
<br />by Max (original by Stephan/Tom 7)
<br /><b>difficulty</b>: 9.42
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/1430"><img src="/png/54c3f177b9d9412d68267d397a90e0ae.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/1430">Newark Liberty Airport (EWR)</a>
<br />by Tom 7
<br /><b>difficulty</b>: 9.37
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/593"><img src="/png/1ac6873beab6b324dbf4bf5951dfadc9.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/593">Bigger Waste of Time</a>
<br />by Max (mod by bpotetz)
<br /><b>difficulty</b>: 9.25
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/692"><img src="/png/b96e9e78ae2af79bb0b62bc1f1baa5fa.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/692">revenge of the computers 2</a>
<br />by pieguy
<br /><b>difficulty</b>: 9.16
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/457"><img src="/png/5361d3a80ab17c2914cca4d65d3697cc.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/457">Hugbot Research Lab</a>
<br />by Joshua Bone
<br /><b>difficulty</b>: 8.85
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/617"><img src="/png/d78a40d89cda1e58e502c3b00ff1865c.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/617">revenge of the computers 1</a>
<br />by pieguy
<br /><b>difficulty</b>: 8.83
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/591"><img src="/png/d80d63ff42c1e193f3ef1a00770d43aa.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/591">Waste of Time</a>
<br />by Max
<br /><b>difficulty</b>: 8.57
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/362"><img src="/png/a4866e383ed6c75ab4a81a87d163cc29.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/362">Memoryless Hole (v3)</a>
<br />by mjn (mod by bpotetz)
<br /><b>difficulty</b>: 8.55
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/2285"><img src="/png/bbb2569bb8c9c430684c3d272bfdc2aa.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/2285">Avalanche 2</a>
<br />by John Lewis (original by pieguy)
<br /><b>difficulty</b>: 8.40
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/1565"><img src="/png/3ebf6495687776b7fe92c23724153ee7.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/1565">revenge of the computers 4</a>
<br />by pieguy
<br /><b>difficulty</b>: 8.40
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/594"><img src="/png/6cead8cdd8fec6e8b8d1cb4fc1b17bcf.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/594">Grand Prix (v3)</a>
<br />by mjn
<br /><b>difficulty</b>: 8.22
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/1517"><img src="/png/e2701f7593d1ee26f0f2bd7cb75c970a.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/1517">Just Enough Block Shortage</a>
<br />by Henri K. (mod by Kirima via John Lewis)
<br /><b>difficulty</b>: 8.20
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/560"><img src="/png/d05c17461a46fa6926fd54d74ccbc3b0.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/560">Time Trap (Maximum Security version)</a>
<br />by Max
<br /><b>difficulty</b>: 8.12
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/442"><img src="/png/f59f53f4d1328dd6d7adefe454ea9abe.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/442">Knight's Tour</a>
<br />by Brian Potetz
<br /><b>difficulty</b>: 8.10
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/311"><img src="/png/b5078714502d1e99ea64d33a6dbb1957.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/311">Crosshairs (the Potetz Variation)</a>
<br />by Brian Potetz (original level by Max)
<br /><b>difficulty</b>: 8.09
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/2027"><img src="/png/b68cd6433b4b5eaad31a44393f030f6f.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/2027">OneLeft (Full Implementation)</a>
<br />by noname (via OCTweak)
<br /><b>difficulty</b>: 8.00
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/669"><img src="/png/70688f10b32af598d07645025cd9c556.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/669">Five Alive</a>
<br />by Tom 7 (+Computer)
<br /><b>difficulty</b>: 8.00
</td></tr>
<tr>
<td valign="top"><a href="/f/a/escape/level/644"><img src="/png/b079c0fa9d35603f5c2d733038dcfe90.png"
border=0></a></td>
<td valign="top"><a href="/f/a/escape/level/644">Roller Coaster (steel)</a>
<br />by mjn
<br /><b>difficulty</b>: 8.00
</td></tr>
</table>
