
default : renderhero.exe

sound.o : sound.c
	gcc -O `sdl-config --cflags` -c sound.c -o sound.o

sdlml.o : ../sdlml/sdlml.c
	gcc -O `sdl-config --cflags` -c ../sdlml/sdlml.c -o sdlml.o

renderhero.exe : sound.o sdlml.o *.sml
	mlton -verbose 1 -link-opt "-lSDL_image -ltiff -lpng -ljpeg -lz `sdl-config --libs`" -default-ann 'allowFFI true' -output renderhero.exe renderhero.cm sound.o sdlml.o

clean :
	rm -f core.* *~ *.exe *.o
