/* Generated by packpng from sound.pack. DO NOT EDIT */

enum sound_t {
     S_REDLIGHT,
     S_GREENLIGHT,
     S_BLUELIGHT,
     S_POWEROFF,
     S_ERROR,
     S_WHIZZ,
     S_CLICK,
     NUM_SOUND,
};

