#                             -*- makefile -*-

songs : bbcscore.mid ng1score.mid popcornscore.mid

ALL = genscore.exe

# add more...
bbcscore.mid : bbc-theme.mid $(ALL)
	./genscore.exe -noxmeasure -history 6 -hammertime 26 $< 0 1 -o $@

ng1score.mid : ng1-1.mid $(ALL)
	./genscore.exe -noxmeasure -history 2 -hammertime 40 $< 0 2 -o $@

popcornscore.mid : popcorn.mid $(ALL)
	./genscore.exe -history 5 -hammertime 40 $< 0 1 3 -o $@
