
var tiles = 
[
 { id: 0, isbg: false, frames: [] },
 { id: 1, isbg: false, frames: ['floor', 1] },
 { id: 2, isbg: true,  frames: ['solidteal', 1] },
 { id: 3, isbg: true,  frames: ['solidtealv1', 1] },
 { id: 4, isbg: true,  frames: ['solidtealv2', 1] },
 { id: 5, isbg: true,  frames: ['solidtealv3', 1] },
 { id: 6, isbg: true,  frames: ['vip1', 1] },
 { id: 7, isbg: true,  frames: ['vip2', 1] },
 { id: 8, isbg: true,  frames: ['cubetop1', 1] },
 { id: 9, isbg: true,  frames: ['cubetop2', 1] },
 { id: 10, isbg: true,  frames: ['cubetop3', 1] },
 { id: 11, isbg: true,  frames: ['cubetop4', 1] },
 { id: 12, isbg: false,  frames: ['cubebot1', 1] },
 { id: 13, isbg: false,  frames: ['cubebot2', 1] },
 { id: 14, isbg: false,  frames: ['cubebot3', 1] },
 { id: 15, isbg: false,  frames: ['cubebot4', 1] },
 { id: 16, isbg: true,  frames: ['restroomsdown', 1] },
 { id: 17, isbg: true,  frames: ['restroomsleft', 1] },
 { id: 18, isbg: true,  frames: ['restrooms2', 1] },
 { id: 19, isbg: true,  frames: ['bathroomtile1', 1] },
 { id: 20, isbg: true,  frames: ['bathroomtile2', 1] },
 { id: 21, isbg: true,  frames: ['bathroomtile3', 1] },
 { id: 22, isbg: true,  frames: ['mirrortl', 1] },
 { id: 23, isbg: true,  frames: ['mirrortr', 1] },
 { id: 24, isbg: true,  frames: ['mirrorbl', 1] },
 { id: 25, isbg: true,  frames: ['mirrorbr', 1] },
 { id: 26, isbg: false,  frames: ['sinkl', 1] },
 { id: 27, isbg: false,  frames: ['sinkr', 1] },
 { id: 28, isbg: false,  frames: ['pipe', 1] },
 { id: 29, isbg: true,  frames: ['stall1', 1] },
 { id: 30, isbg: true,  frames: ['stall2', 1] },
 { id: 31, isbg: true,  frames: ['stall3', 1] },
 { id: 32, isbg: true,  frames: ['stall4', 1] },
 { id: 33, isbg: true,  frames: ['stall5', 1] },
 { id: 34, isbg: true,  frames: ['stall6', 1] },
 { id: 35, isbg: true,  frames: ['stall7', 1] },
 { id: 36, isbg: true,  frames: ['stall8', 1] },
 { id: 37, isbg: true,  frames: ['stall9', 1] },
 { id: 38, isbg: true,  frames: ['stall10', 1] },
 { id: 39, isbg: true,  frames: ['stallsolid', 1] },
 { id: 40, isbg: true,  frames: ['ooo1', 1] },
 { id: 41, isbg: true,  frames: ['ooo2', 1] },
 { id: 42, isbg: true,  frames: ['ooo3', 1] },
 { id: 43, isbg: true,  frames: ['ooo4', 1] },
 { id: 44, isbg: true,  frames: ['ooo5', 1] },
 { id: 45, isbg: true,  frames: ['ooo6', 1] },
 { id: 46, isbg: true,  frames: ['ooo7', 1] },
 { id: 47, isbg: true,  frames: ['ooo8', 1] },
 { id: 48, isbg: true,  frames: ['ooo9', 1] },
 { id: 49, isbg: true,  frames: ['ooo10', 1] },
 { id: 50, isbg: true,  frames: ['ooo11', 1] },
 { id: 51, isbg: true,  frames: ['dirt1', 1] }
 ];
