
wget http://download.geofabrik.de/north-america/us/alabama-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/alaska-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/arizona-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/arkansas-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/california-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/colorado-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/connecticut-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/delaware-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/district-of-columbia-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/florida-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/georgia-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/hawaii-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/idaho-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/illinois-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/indiana-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/iowa-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/kansas-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/kentucky-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/louisiana-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/maine-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/maryland-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/massachusetts-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/michigan-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/minnesota-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/mississippi-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/missouri-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/montana-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/nebraska-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/nevada-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/new-hampshire-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/new-jersey-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/new-mexico-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/new-york-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/north-carolina-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/north-dakota-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/ohio-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/oklahoma-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/oregon-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/pennsylvania-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/rhode-island-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/south-carolina-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/south-dakota-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/tennessee-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/texas-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/utah-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/vermont-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/virginia-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/washington-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/west-virginia-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/wisconsin-latest.osm.bz2
wget http://download.geofabrik.de/north-america/us/wyoming-latest.osm.bz2
