
default : test.exe

sdlml.o : sdlml.c
	gcc -DLINUX -O `sdl-config --cflags` -c sdlml.c -o sdlml.o

sdlnet.o : sdlnet.c
	gcc -DLINUX -O `sdl-config --cflags` -c sdlnet.c -o sdlnet.o

test.exe : sdlml.o sdlnet.o *.sml
	mlton -link-opt "-lSDL_image -lSDL_net -ltiff -lpng -ljpeg -lz `sdl-config --libs`" -default-ann 'allowFFI true' -output test.exe test.cm sdlml.o sdlnet.o

# -lSDL_net

clean :
	rm -f core.* *~ *.exe *.o
